name: particletracking
channels:
    - conda-forge
    - teokem
dependencies:
    - python=3.6
    - numpy=1.19
    - scipy=1.2
    - pandas=1.1
    - matplotlib=3.2
    - trackpy=0.5
    - pims=0.5
    - jupyter=1.0
    - notebook=5.7
    - ffmpeg=4.3
    - mdtraj=1.9
    - faunus
