name: particletracking
channels:
    - conda-forge
dependencies:
    - python=2
    - numpy=1.13
    - scipy=1.0
    - pandas=0.21
    - matplotlib=2.1
    - trackpy=0.3.3
    - pims=0.4
    - jupyter
    - notebook
    - ffmpeg=3.2
