name: particletracking
channels:
    - conda-forge
dependencies:
    - python=3.9
    - numpy=1
    - scipy=1.10
    - pandas=1.5
    - matplotlib=3.6
    - trackpy=0.5
    - pims=0.6
    - notebook=6.5
    - ffmpeg=5
    - mdtraj=1.9
    - faunus
    - jupyterlab=3.5
    - jupyterlab_widgets=3.0
