name: particletracking
channels:
    - conda-forge
dependencies:
    - python=3.9
    - numpy=1.13
    - scipy=1
    - pandas=0.22
    - matplotlib=2.1
    - trackpy=0.5
    - pims
    - jupyter
    - notebook
    - ffmpeg=3
    - mdtraj=1.9
    - faunus
