name: particletracking
channels:
    - defaults
    - conda-forge
dependencies:
    - python=2.7
    - numpy=1.13
    - scipy=1.0
    - pandas=0.21
    - matplotlib=2.1
    - trackpy=0.3.3
    - pims=0.4
    - jupyter=1.0
    - notebook=5.2
    - ffmpeg=3.2
