name: particletracking
dependencies:
    - black
    - cryptography
    - faunus=2
    - ffmpeg=5
    - isort
    - jupyterlab
    - jupyterlab_widgets=3
    - matplotlib=3
    - mdtraj=1.9
    - notebook
    - numpy=1
    - pandas=1
    - pims=0.6
    - python=3
    - ruff
    - scipy=1
    - trackpy=0.6
    - pip:
        jupyterlab-code-formatter
    
